### ISSUE TITLE
WebVault 2.16 throws a 404 when building trying to create an organisation.

### ISSUE THREAD

**Issue by kinsago** [dani-garcia/bitwarden_rs#1144]
Hi all,

I've built web-vault 2.16 a few times and each time I'm unable to create an organisation from within the web vault (It hangs with "/api/plans/:1 Failed to load resource: the server responded with a status of 404 ()").  Having tried to resolve this for a few days, today I deleted the web-vault folder on my server and compiled 2.15.1 (following the same steps as before) which seems to have worked first time.  I'm therefore wondering if there's something in 2.16 that's broken?

Instructions I followed for compiling are on this website https://pieterhollander.nl/post/bitwarden.  Server is Debian 10.

Thanks,
Phil

**Comment by dinger1986** [comment]
I built a script to install https://github.com/dinger1986/bitwardenrs_install_script using 2.16 and compiling fine for me. works on ubuntu 20.04.

The issue with the organisation was fixed yesterday, if you have done all the prerequisites you could use the update script I have written and just remove the ubuntu check?

**Comment by kinsago** [comment]
Thanks - I'll give it a go later and report back.

Thanks for the quick response.

Phil

**Comment by BlackDex** [comment]
This was a bug and already fixed in the latest version.

**Comment by kinsago** [comment]
Hi all,

Apologies for the delay, I was away for a few days.  I've recompiled web-vault this morning using the latest version of the vault and patch 2.16.0 and it's still showing the same problem.  I've reverted back to 2.15.1 for now. I did have to manually wget the 2.16.0 so I wonder if the bitwarden webvault has been updated again?

I forgot to mention, I'm compiling on a Ubuntu 14.04 server and running on a Debian 10 server (my Debian box doesn't have enough grunt to compile).  I don't *think* it's relevant as the previous version of webvault compiles and runs without issues and compiling 2.16.0 doesn't generate any errors.

**Comment by kinsago** [comment]
Hi,

```
git clone https://github.com/bitwarden/web.git
cd web
git checkout "$(git tag --sort=v:refname | tail -n1)" # checkout most recent version
```
Looking back through the console output, this is indeed a new version "Note: switching to 'v2.16.1'."

I then use 

`wget https://raw.githubusercontent.com/dani-garcia/bw_web_builds/master/patches/$(git tag --sort=v:refname | tail -n1).patch`

which returns a 404 (makes sense as I'm now on v2.16.1) so I then manually wget the 2.16.0 patch.

`wget https://raw.githubusercontent.com/dani-garcia/bw_web_builds/master/patches/v2.16.0.patch`

and apply it with 
`git apply v2.16.0.patch`

Hope this helps.

**Comment by dinger1986** [comment]
I also tried the same but used this to check out etc:

#Compile bitwarden_rs
git clone https://github.com/dani-garcia/bitwarden_rs.git
cd bitwarden_rs/
git checkout
cargo build --features sqlite --release
cd ..

#Clone and checkout repository for Bitwarden web and patch
git clone https://github.com/bitwarden/web.git
cd web
git checkout
wget https://raw.githubusercontent.com/dani-garcia/bw_web_builds/master/patches/$(git tag --sort=v:refname | tail -n1).patch
git apply $(git tag --sort=v:refname | tail -n1).patch

**Comment by dinger1986** [comment]
you can also download the latest precompiled web-build from here https://github.com/dani-garcia/bw_web_builds/releases

**Comment by kinsago** [comment]
I'll try the precompiled web-build and confirm later.

**Comment by BlackDex** [comment]
If you see a 404 error it probably is the `/api/plans` link.
If that is the case you probably still have an older version of bitwarden_rs since that is fixed in the latest version

**Comment by kinsago** [comment]
Thanks all, recompiling and redeploying the server and the web-vault seems to have resolved this for v2.16.0
