### ISSUE TITLE
Wrong Master password unless I logout and re-login

### ISSUE THREAD

**Issue by mind-overflow** [dani-garcia/bitwarden_rs#1216]
As already mentioned in the official Bitwarden forum, the new Bitwarden version inclused fundamental API changes that break login in extensions, desktop apps, etc...
Fortunately, logging in still works if you click "Disconnect" before attempting to enter the password.
These API changes need to be implemented directly into the server.
Related thread: [here](https://community.bitwarden.com/t/self-hosted-master-password-only-works-after-logout/15231).

**Comment by BlackDex** [comment]
This has been fixed over a month ago in #1158 .
Please update your bitwarden_rs to the latest version available, see: #1180

**Comment by mind-overflow** [comment]
Understood. I have updated it to 2.16.1 a few hours ago and was still getting the error, so that's why I opened the issue. I guess it was because of caching. Sorry for the trouble!
