### ISSUE TITLE
Icon caching problem or time out fetching icon

### ISSUE THREAD

**Issue by BobWs** [dani-garcia/bitwarden_rs#390]
I have a similar problem with icon caching. This happened a few updates ago. I don't know exactly when. But when I check the log this is what I see.

`}
stdout
12:53:12
[2019-02-10 12:53:12][bitwarden_rs::api::icons][ERROR] Error downloading icon: ReqError.
stdout
12:53:12
[CAUSE] Error {
stdout
12:53:12
    kind: Io(
stdout
12:53:12
        Custom {
stdout
12:53:12
            kind: WouldBlock,
stdout
12:53:12
            error: StringError(
stdout
12:53:12
                "timed out"
stdout
12:53:12
            )
stdout
12:53:12
        }
stdout
12:53:12
    ),
stdout
12:53:12
    url: Some(
stdout
12:53:12
        "https://www.oneplus.com/favicon.ico"
stdout
12:53:12
    )
stdout
12:53:12
}`

Also when looking in the icon_cache folder I see the missing icons named like this: `www.oneplus.com.png.miss`

Any idea how to fix this?

_Originally posted by @BobWs in https://github.com/dani-garcia/bitwarden_rs/issues/292#issuecomment-462132916_

**Comment by dani-garcia** [comment]
It seems to load fine for me, the problem might be that with the recent change to icons we reduced the timeout of the requests to 5 seconds (from a default of 30) to avoid keeping the clients waiting a long time. If you have a slow connection with the icon server, you might get a timeout error like you did. Do other icons load fine?

**Comment by mprasil** [comment]
I think we should make this timeout configurable, 5s might be way to low for some users. (or websites)

@BobWs: just to explain the *.miss file. This is used by negative cache - when *.miss file exists for a domain, bitwarden_rs won't try to fetch it for ICON_CACHE_NEGTTL seconds - by default 259200 seconds. (3 days) The point of this is so that pages that constantly fail providing icons won't be queried on every single request. You can delete the *.miss file to force bitwarden_rs to attempt downloading the icon again when it's requested next time.

**Comment by mprasil** [comment]
BTW, there is also a problem of Vault spinning tons of requests at once for the favicons. Last time I saw it discussed [here](https://github.com/bitwarden/web/issues/217#issuecomment-406538396). Now rocket is not async (yet) so we're technically limited by number of workers to serve the requests. By default we set it to [10](https://github.com/dani-garcia/bitwarden_rs/blob/bbe2a1b264b5ef4d8eba6643857a03e905ff9dec/Dockerfile#L65) which (in combination with bitwarden_rs having to fetch the external resources) might be too low to handle hundreds of requests (one for each password) if the icons aren't already cached. Connecting directly is probably not really a problem, browser will wait, but I wonder if proxy might be a bit impatient and drop the "non responsive" backend in your case? Try to delete the icon cache and set the `ROCKET_WORKERS` to some higher number?

**Comment by BobWs** [comment]
> It seems to load fine for me, the problem might be that with the recent change to icons we reduced the timeout of the requests to 5 seconds (from a default of 30) to avoid keeping the clients waiting a long time. If you have a slow connection with the icon server, you might get a timeout error like you did. Do other icons load fine?

Some icons load just fine but the majority doesn’t load. I don’t have a slow internet connection to be clear (200Mb/20Mb)

**Comment by mprasil** [comment]
When you say doesn't load, do you mean you get these timeout errors?

**Comment by BobWs** [comment]
Yes I get these errors.  And I see only the default globe

**Comment by mprasil** [comment]
Does this happen for all icons or just some?

**Comment by BlackDex** [comment]
I will go and create a configurable timeout

**Comment by BlackDex** [comment]
Well this should be fixed in #394 . You can now change the timeout value if needed.
It is also changed from 5 to 10 seconds.

**Comment by mprasil** [comment]
The image is just being built, in about an hour you can use `mprasil/bitwarden:latest` that will have the timeout set to 10 and you can experiment with raising the value even higher. See if the problem still persists with that.

**Comment by BobWs** [comment]
> The image is just being built, in about an hour you can use `mprasil/bitwarden:latest` that will have the timeout set to 10 and you can experiment with raising the value even higher. See if the problem still persists with that.

So how do I change the timeout? Where can I find the setting? 

So far I have updated the build and some of the icon which didn’t load before are now loading, but there are a few who still doesn’t load.

And the error message mentioned above I haven’t seen it anymore in the logs..

**Comment by mprasil** [comment]
Okay, so try to delete the `*.miss` files, that should let `bitwarden_rs` try again. Alternatively delete whole icon cache if you feel like trying to download all icons again. 😉

Just try the new image as it is, it's already set to 10 seconds timeout.

**Comment by BobWs** [comment]
Okay so I deleted the `*miss` Files but after login in bitwarden they reappear. 

So after further investigation I found out that changing the domain the icons start loading. e.g. if I have a domain like this  `https://account.protonvpn.com/login/` the icons don’t seem to load but after changing the domain to `protonvpn.com` the icons starts to load. 

This is very strange because it was working before.

**Comment by BlackDex** [comment]
what does the log say for account.protonvpn.com??
it works for me btw.

**Comment by BobWs** [comment]
Sorry for the delay, I found this in the logs:

`
2019-02-13 21:21:27,stdout,[2019-02-13 21:21:27][bitwarden_rs::api::icons][ERROR] Error downloading icon: Empty response. Empty response
2019-02-13 21:21:27,stdout,[2019-02-13 21:21:27][bitwarden_rs::api::icons][INFO] Download failed for
https://www.account.protonvpn.com/favicon.ico
2019-02-13 21:21:17,stdout,[2019-02-13 21:21:17][bitwarden_rs::api::icons][INFO] Downloading icon for www.account.protonvpn.com via https://www.account.protonvpn.com/favicon.ico...
2019-02-13 19:03:56,stdout,[2019-02-13 19:03:56][bitwarden_rs::api::icons][ERROR] Error downloading icon: Empty response. Empty response
2019-02-13 19:03:56,stdout,[2019-02-13 19:03:56][bitwarden_rs::api::icons][INFO] Download failed for https://www.noip.com/favicon.ico
2019-02-13 19:03:56,stdout,[2019-02-13 19:03:56][bitwarden_rs::api::icons][ERROR] Error downloading icon: Empty response. Empty response
2019-02-13 19:03:56,stdout,[2019-02-13 19:03:56][bitwarden_rs::api::icons][INFO] Download failed for https://account.synology.com/favicon.ico`

**Comment by BlackDex** [comment]
Well, www.account.protonvpn.com doesn't work, so that isn't strange.
But www.noip.com and account.synology.com both work for me.

I suggest to increase the timeout a bit more.
This can be done a few ways.
- Via the /admin pannel (When using the latest build image)
- Via the docker run command using `-e ICON_DOWNLOAD_TIMEOUT 20`

This timeout is also used for fetching the main page of the website to extract all the icon URL's, so if fetching that takes longer it would also timeout.

**Comment by mprasil** [comment]
@BobWs did you try increasing the timeout? Did that resolve your issue?

**Comment by mprasil** [comment]
I'm going to close this with hope that @BobWs has resolved his issue. Feel free to reopen if it's still a problem.

**Comment by BobWs** [comment]
> I'm going to close this with hope that @BobWs has resolved his issue. Feel free to reopen if it's still a problem.

It is partly solved.  Some days I have all the icons an some days the icons are gone and I have the default globe. Even when I clear out the cache folder. So I can’t figure out the problem.

**Comment by mprasil** [comment]
Thanks for update. I suspect the failures are happening for some network-related reason. Maybe you could improve the situation by setting the `ICON_CACHE_TTL=0` which will keep the already downloaded icons forever (standard is 30 days) so once it succeeds, it will keep them forever.

You can also lower the `ICON_CACHE_NEGTTL` to something like `86400` (one day in seconds, default is 3 days) so that it will attempt to download the icons at least once a day.

Over time you should build pretty solid cache with very few outstanding icon misses. See [here](https://github.com/dani-garcia/bitwarden_rs/blob/5794969f5bfdf52fa1f8c098579d71cc87682f44/.env.template#L19-L22) for brief description of the settings.

**Comment by BobWs** [comment]
> Thanks for update. I suspect the failures are happening for some network-related reason. Maybe you could improve the situation by setting the `ICON_CACHE_TTL=0` which will keep the already downloaded icons forever (standard is 30 days) so once it succeeds, it will keep them forever.
> 
> You can also lower the `ICON_CACHE_NEGTTL` to something like `86400` (one day in seconds, default is 3 days) so that it will attempt to download the icons at least once a day.
> 
> Over time you should build pretty solid cache with very few outstanding icon misses. See [here](https://github.com/dani-garcia/bitwarden_rs/blob/5794969f5bfdf52fa1f8c098579d71cc87682f44/.env.template#L19-L22) for brief description of the settings.

Thanks I will give it a try. Could you please tell me what the command is for changing these settings. I’m not that familiar with docker yet.

Thanks for the effort

**Comment by mprasil** [comment]
Just restart your container with the variables set. The usual `docker stop ...; docker rm ...; docker run ...;`, but remember to provide your variables. Alternatively you can set these in the admin interface.

**Comment by BobWs** [comment]
> Just restart your container with the variables set. The usual `docker stop ...; docker rm ...; docker run ...;`, but remember to provide your variables. Alternatively you can set these in the admin interface.

I have set the variables as you suggested `ICON_CACHE_TTL=0` and `ICON_CACHE_NEGTTL=86400` This is working the icons are all showing, but When the container/image is updated these variables are gone and I have to start over again.

Any suggestions how to keep them permanently set?

**Comment by BlackDex** [comment]
How did you set these variables?
Did you do that `docker run ... -e ICON_CACHE_TTL=0 -e ICON_CACHE_NEGTTL=86400 ...`
Or via the `/admin` panel?

Because if you use the environment option, you need to do that always at every `docker run` when  you have updated it.

**Comment by BobWs** [comment]
I'm using the docker GUI of Synology (See attachment)

![Screen Shot 2019-03-25 at 13 52 19](https://user-images.githubusercontent.com/5485820/54921157-5a4df500-4f05-11e9-9ea9-ff600cf21c18.png)

**Comment by BlackDex** [comment]
Well, i have no idea how that works.
Maybe also try to add it via the admin panel then, that will override the other settings.

**Comment by BobWs** [comment]
What Admin panel? Where can I find it? When login to the Webpage of bitwarden I don't see a admin panel.

**Comment by BobWs** [comment]
I'm using this script to auto update the bitwarden image every week:

`docker pull mprasil/bitwarden:latest
docker stop bitwarden
docker rm bitwarden
docker run -d --name bitwarden -v /volume1/docker/bitwarden/bw-data/:/data/ -p 81:80 mprasil/bitwarden:latest`

Can I implement to set the variables in this script when updating the image? How do I do that?

**Comment by dani-garcia** [comment]
You can either add the options in that `docker run` command like this:
```
docker pull mprasil/bitwarden:latest
docker stop bitwarden
docker rm bitwarden
docker run -d --name bitwarden -e ICON_CACHE_TTL=0 -e ICON_CACHE_NEGTTL=86400  -v /volume1/docker/bitwarden/bw-data/:/data/ -p 81:80 mprasil/bitwarden:latest
```

Or you can enable the admin panel and set the options from there, which is permanent:
```
docker pull mprasil/bitwarden:latest
docker stop bitwarden
docker rm bitwarden
docker run -d --name bitwarden -e ADMIN_TOKEN=some_secure_password  -v /volume1/docker/bitwarden/bw-data/:/data/ -p 81:80 mprasil/bitwarden:latest
```

And then the admin panel should be available from `your_domain/admin`.

**Comment by BlackDex** [comment]
Ah, if you go to the URL of your bitwarden_rs location https://bwrs.example.com/admin
You will see the admin panel.
You need to give a token before you can access this.
That token can be set via the "environment" by setting `ADMIN_TOKEN`.
Make it a long string of random numbers and letters.

**Comment by BobWs** [comment]
> You can either add the options in that `docker run` command like this:
> 
> ```
> docker pull mprasil/bitwarden:latest
> docker stop bitwarden
> docker rm bitwarden
> docker run -d --name bitwarden -e ICON_CACHE_TTL=0 -e ICON_CACHE_NEGTTL=86400  -v /volume1/docker/bitwarden/bw-data/:/data/ -p 81:80 mprasil/bitwarden:latest
> ```
> Or you can enable the admin panel and set the options from there, which is permanent:
> 
> ```
> docker pull mprasil/bitwarden:latest
> docker stop bitwarden
> docker rm bitwarden
> docker run -d --name bitwarden -e ADMIN_TOKEN=some_secure_password  -v /volume1/docker/bitwarden/bw-data/:/data/ -p 81:80 mprasil/bitwarden:latest
> ```
> And then the admin panel should be available from `your_domain/admin`.

Okay I will give it a try

**Comment by BobWs** [comment]
Okay it is set! I have enabled the Admin page and set the variables, so now it should be permanent even after an update..right!?

Thank you all for your support

**Comment by mprasil** [comment]
It should create config file in the data directory. If that file is preserved, so will be the configuration.

**Comment by labaland** [comment]
I just installet image: bitwardenrs/server:latest in docker on my synology nas. Works good but it cant download any icons:
Tested all settings above, then it did not try to download any. Sorry for my bad english.

```
[2020-08-15 13:44:39.621][request][INFO] GET /icons/www.gd.se/icon.png
[2020-08-15 13:45:16.257][bitwarden_rs::api::icons][INFO] Download failed for https://www.gd.se/favicon.ico
[2020-08-15 13:45:36.269][bitwarden_rs::api::icons][INFO] Download failed for http://www.gd.se/favicon.ico
[2020-08-15 13:45:36.269][bitwarden_rs::api::icons][ERROR] Error downloading icon: Empty response
[2020-08-15 13:45:36.269][response][INFO] GET /icons/<domain>/icon.png (icon) => 200 OK
[2020-08-15 13:45:49.654][bitwarden_rs::api::icons][INFO] Download failed for https://www.gd.se/favicon.ico
[2020-08-15 13:46:09.665][bitwarden_rs::api::icons][INFO] Download failed for http://www.gd.se/favicon.ico
[2020-08-15 13:46:09.665][bitwarden_rs::api::icons][ERROR] Error downloading icon: Empty response
```

**Comment by BlackDex** [comment]
@labaland This issue has already been closed, please create a new one, or even better go to the forum https://bitwardenrs.discourse.group/

Also, the "latest" tag isn't the latest any more, please us the tag "testing".
And try to check the "/admin/diagnostics" page to see if  you have internet at all.

If you still need help, please go to the forums.

**Comment by labaland** [comment]
> @labaland 
> Also, the "latest" tag isn't the latest any more, please us the tag "testing".
> And try to check the "/admin/diagnostics" page to see if you have internet at all.

Thank you for answering me  :)
using testing now. see picture : 
[https://imgur.com/Z7oPSS5](url)
