### ISSUE TITLE
iOS app bitwarden doesn’t sync anymore 

### ISSUE THREAD

**Issue by BobWs** [dani-garcia/bitwarden_rs#554]
Hi,

Has anybody noticed or problems with syncing new or changed items in Bitwarden on iOS devices? 

Every time I create I new item or change an item in Bitwarden they aren’t synced on refreshing or closing the app. I have to do a manual sync to save them to the server. And when I open the Bitwarden app on another iOS device the changes don’t sync either I have to do it manually.

This seems to have started after the app update of mid June. Before it was working perfectly.

I don’t have an Android device to test so I don’t know if this problem is iOS related or a server problem.

**Comment by uchagani** [comment]
I have this same issue.  I have to manually sync to get updates that i met hours/days before.

**Comment by dani-garcia** [comment]
By changed do you mean changed in other devices but the changes don’t propagate to the iOS client?
In that case it could be because push notifications aren’t implemented, but that would also apply to the previous versions.

It’s possible older versions forced an update while login and they don’t anymore, I’m not sure. My main device is an iPhone but I don’t make changes to items often enough to notice sync problems.

**Comment by uchagani** [comment]
@dani-garcia from my experience, if i create an entry on my computer I can't see those changes on my iOS client (even hours later) without doing a manual sync.  I have notifications for Bitwarden turned on.  

Versions:
Bitwarden_rs: Version 2.10.1
iOS client: latest from app store

**Comment by BobWs** [comment]
I have noticed that BW sync is still working fine on an older iOS (10) device with BW client version 1.12. So I guess the bug is either related to the latest version of BW client or Apple broke something again with the latest iOS version (12.4).

**Comment by BobWs** [comment]
@uchagani Question, Have you already reported this bug to the official BW community site?

**Comment by uchagani** [comment]
I haven't.

**Comment by BobWs** [comment]
> I haven't.
> […](#)

Okay I will report the bug

**Comment by vverst** [comment]
Seems like it was fixed.
```
Version 2.2.1
Fix some sync issues
Crash and other bug fixes
```

It seems to sync more often now.

**Comment by BobWs** [comment]
> Seems like it was fixed.
> 
> ```
> Version 2.2.1
> Fix some sync issues
> Crash and other bug fixes
> ```
> 
> It seems to sync more often now.

No still not fixed one can follow the discussion here https://community.bitwarden.com/t/ios-problem-syncing-ios-app-broken-after-latest-update/7372

**Comment by vverst** [comment]
> No still not fixed one can follow the discussion here https://community.bitwarden.com/t/ios-problem-syncing-ios-app-broken-after-latest-update/7372

Before the 2.2.1 Bitwarden iOS update I was having problems with syncing; I had to manually click Sync for it to work otherwise the app would go days without up to date information.

My syncing issue went away with the 2.2.1 update. Now it takes some time but when I open the app after 40 minutes it will have the latest information. It's not possible to get instantaneous updates since push updates are not possible from bitwarden_rs to the iOS client.

I'm running the latest bitwarden_rs server (`1.10.0-469318bc`) and running iOS 13.1 public beta.

In the thread you linked you don't mention that you're using bitwarden_rs and therefore can't use the push notification server. This might confuse kspearrin to think there is something wrong with the push notifications and the iOS client while there probably is not. I think it would be helpful for him to know that you cannot use the push notification route for updates and instead are looking for a "fetch" from the iOS client to the self-hosted server.

Have you also tested the official self-hosted Bitwarden server?

**Comment by BobWs** [comment]
You are right I didn’t mention that I’m using the rs version, but most of all the other people who are complaining that the sync is not working are on the official BW. Also I have read similar complaints on Reddit about this. And as I stated before with the older version of iOS BW client (1.*.*) it was working fine. (And still is on a older iOS device with iOS 10 an BW client 1.*.*)

**Comment by bigtarget** [comment]
Will that be solved in near future?

**Comment by dani-garcia** [comment]
Closed due to inactivity. Some sync problems with mobile apps have been solved recently.
